# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'VCC_FinanceEngine', '1.0.0'

  # Pods for DemoPod

end
